install.packages("readxl")
library(readxl)
Suwon_Drugstore<- read_excel("C:/Rstudy/수원시_약국_가공.xlsx")
head(Suwon_Drugstore)
View(Suwon_Drugstore)
addr <- substr(Suwon_Drugstore$도로명전체주소, 9,16)
head(addr)
addr_num <- gsub("[0-9]","",addr)
addr_trim <- gsub(" ","",addr_num)
head(addr_trim)

install.packages('dplyr')
library(dplyr)
addr_count <- addr_trim %>% table() %>% data_frame()
head(addr_count)
View(addr_count)
install.packages("treemap")
library(treemap)
treemap(addr_count,index= "." , vSize = "Freq", title = "수원시 약국 분표")

